name: mlflow-env

channels:
  - defaults

dependencies:
  - python=3.10
  - pip

  - pip:
      - tensorflow
      - mlflow
      - dagshub
      - numpy
      - matplotlib
      - scikit-learn
      - pillow
